### ISSUE TITLE
您好，运行出错，解析编码的部分。请问有什么方法可以解决吗？谢谢！

### ISSUE THREAD

**Issue by byezhao** [mikami-yua/-#2]
`def parser_content(msg):
    content = msg.get_payload()
    

    content_charset = content[0].get_content_charset() # 获取编码格式
    text = content[0].as_string().split('base64')[-1]
    text_content = base64.b64decode(text).decode(content_charset) # base64解码
`
pycharm 出错报告：
Traceback (most recent call last):
  File "C:\Users\CMSS\Desktop\项目\byes_mail_filter-main\get_mail.py", line 101, in <module>
    parser_content(msg)
  File "C:\Users\CMSS\Desktop\项目\byes_mail_filter-main\get_mail.py", line 79, in parser_content
    content_charset = content[0].get_content_charset() # 获取编码格式
AttributeError: 'str' object has no attribute 'get_content_charset'

邮箱设置是正确的；
请问大佬可以帮忙解决一下吗

**Comment by byezhao** [comment]
换了个邮件内容，好了。。原来之前那个邮件内容可能不支持解码什么的。。。

**Comment by LiuYuJie09** [comment]
> 换了个邮件内容，好了。。原来之前那个邮件内容可能不支持解码什么的。。。

怎么换的呀，兄弟
